# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
