# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Is the account business or personal?
  class AccountClassification1Enum
    ACCOUNT_CLASSIFICATION1_ENUM = [
      # TODO: Write general description for PERSONAL
      PERSONAL = 'Personal'.freeze,

      # TODO: Write general description for BUSINESS
      BUSINESS = 'Business'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACCOUNT_CLASSIFICATION1_ENUM.include?(value)
    end
  end
end
