# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # AccountClassification.
  class AccountClassificationEnum
    ACCOUNT_CLASSIFICATION_ENUM = [
      # TODO: Write general description for PERSONAL
      PERSONAL = 'personal'.freeze,

      # TODO: Write general description for BUSINESS
      BUSINESS = 'business'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACCOUNT_CLASSIFICATION_ENUM.include?(value)
    end
  end
end
