# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # AccountNumber Model.
  class AccountNumber < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Relationships]
    attr_accessor :relationships

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['relationships'] = 'relationships'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        id
        relationships
        type
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(id = SKIP,
                   relationships = SKIP,
                   type = SKIP)
      @id = id unless id == SKIP
      @relationships = relationships unless relationships == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      relationships = Relationships.from_hash(hash['relationships']) if hash['relationships']
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      AccountNumber.new(id,
                        relationships,
                        type)
    end
  end
end
