# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # AccountRelationships Model.
  class AccountRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :account_events

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :master_account

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_events'] = 'account_events'
      @_hash['master_account'] = 'master_account'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_events
        master_account
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(account_events = SKIP,
                   master_account = SKIP)
      @account_events = account_events unless account_events == SKIP
      @master_account = master_account unless master_account == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_events = RelationshipLinks.from_hash(hash['account_events']) if
        hash['account_events']
      master_account = RelationshipLinks.from_hash(hash['master_account']) if
        hash['master_account']

      # Create object from extracted values.
      AccountRelationships.new(account_events,
                               master_account)
    end
  end
end
