# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # AccountSwitching.
  class AccountSwitchingEnum
    ACCOUNT_SWITCHING_ENUM = [
      # TODO: Write general description for FULL
      FULL = 'full'.freeze,

      # TODO: Write general description for PARTIAL
      PARTIAL = 'partial'.freeze,

      # TODO: Write general description for INELIGIBLE
      INELIGIBLE = 'ineligible'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ACCOUNT_SWITCHING_ENUM.include?(value)
    end
  end
end
