# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Attributes59 Model.
  class Attributes59 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # [Status](http://draft-api-docs.form3.tech/api.html#enumerations-payment-st
    # atus-codes-payment-submission-status) of the submission
    # @return [RecallDecisionSubmissionStatusEnum]
    attr_accessor :status

    # Reason for submission failure if status is `delivery_failed`
    # @return [String]
    attr_accessor :status_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['status_reason'] = 'status_reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
        status_reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = SKIP,
                   status_reason = SKIP)
      @status = status unless status == SKIP
      @status_reason = status_reason unless status_reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP
      status_reason = hash.key?('status_reason') ? hash['status_reason'] : SKIP

      # Create object from extracted values.
      Attributes59.new(status,
                       status_reason)
    end
  end
end
