# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Attributes55 Model.
  class Attributes55 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Current limit
    # @return [String]
    attr_accessor :limit

    # Current position
    # @return [String]
    attr_accessor :position

    # Scheme associated with the limit
    # @return [String]
    attr_accessor :scheme

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['limit'] = 'limit'
      @_hash['position'] = 'position'
      @_hash['scheme'] = 'scheme'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        limit
        position
        scheme
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(limit = SKIP,
                   position = SKIP,
                   scheme = SKIP)
      @limit = limit unless limit == SKIP
      @position = position unless position == SKIP
      @scheme = scheme unless scheme == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      limit = hash.key?('limit') ? hash['limit'] : SKIP
      position = hash.key?('position') ? hash['position'] : SKIP
      scheme = hash.key?('scheme') ? hash['scheme'] : SKIP

      # Create object from extracted values.
      Attributes55.new(limit,
                       position,
                       scheme)
    end
  end
end
