# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Form3PublicApi
  # Attributes4 Model.
  class Attributes4 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [AdviceSubmissionStatusEnum]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status_reason

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :submission_datetime

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :transaction_start_datetime

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['status_reason'] = 'status_reason'
      @_hash['submission_datetime'] = 'submission_datetime'
      @_hash['transaction_start_datetime'] = 'transaction_start_datetime'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status
        status_reason
        submission_datetime
        transaction_start_datetime
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = SKIP,
                   status_reason = SKIP,
                   submission_datetime = SKIP,
                   transaction_start_datetime = SKIP)
      @status = status unless status == SKIP
      @status_reason = status_reason unless status_reason == SKIP
      @submission_datetime = submission_datetime unless submission_datetime == SKIP
      unless transaction_start_datetime == SKIP
        @transaction_start_datetime =
          transaction_start_datetime
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : SKIP
      status_reason = hash.key?('status_reason') ? hash['status_reason'] : SKIP
      submission_datetime = if hash.key?('submission_datetime')
                              (DateTimeHelper.from_rfc3339(hash['submission_datetime']) if hash['submission_datetime'])
                            else
                              SKIP
                            end
      transaction_start_datetime = if hash.key?('transaction_start_datetime')
                                     (DateTimeHelper.from_rfc3339(hash['transaction_start_datetime']) if hash['transaction_start_datetime'])
                                   else
                                     SKIP
                                   end

      # Create object from extracted values.
      Attributes4.new(status,
                      status_reason,
                      submission_datetime,
                      transaction_start_datetime)
    end

    def to_custom_submission_datetime
      DateTimeHelper.to_rfc3339(submission_datetime)
    end

    def to_custom_transaction_start_datetime
      DateTimeHelper.to_rfc3339(transaction_start_datetime)
    end
  end
end
