# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # BankIDCode1.
  class BankIDCode1Enum
    BANK_ID_CODE1_ENUM = [
      # TODO: Write general description for GBDSC
      GBDSC = 'GBDSC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      BANK_ID_CODE1_ENUM.include?(value)
    end
  end
end
