# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # BankIdCode.
  class BankIdCodeEnum
    BANK_ID_CODE_ENUM = [
      # TODO: Write general description for SWBIC
      SWBIC = 'SWBIC'.freeze,

      # TODO: Write general description for GBDSC
      GBDSC = 'GBDSC'.freeze,

      # TODO: Write general description for BE
      BE = 'BE'.freeze,

      # TODO: Write general description for FR
      FR = 'FR'.freeze,

      # TODO: Write general description for DEBLZ
      DEBLZ = 'DEBLZ'.freeze,

      # TODO: Write general description for GRBIC
      GRBIC = 'GRBIC'.freeze,

      # TODO: Write general description for ITNCC
      ITNCC = 'ITNCC'.freeze,

      # TODO: Write general description for PLKNR
      PLKNR = 'PLKNR'.freeze,

      # TODO: Write general description for PTNCC
      PTNCC = 'PTNCC'.freeze,

      # TODO: Write general description for ESNCC
      ESNCC = 'ESNCC'.freeze,

      # TODO: Write general description for CHBCC
      CHBCC = 'CHBCC'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      BANK_ID_CODE_ENUM.include?(value)
    end
  end
end
