# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # CallbackURI Model.
  class CallbackURI < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [CallbackTransportEnum]
    attr_accessor :callback_transport

    # URI that will be called with the notification
    # @return [String]
    attr_accessor :callback_uri

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['callback_transport'] = 'callback_transport'
      @_hash['callback_uri'] = 'callback_uri'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(callback_transport = nil,
                   callback_uri = nil)
      @callback_transport = callback_transport
      @callback_uri = callback_uri
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      callback_transport =
        hash.key?('callback_transport') ? hash['callback_transport'] : nil
      callback_uri = hash.key?('callback_uri') ? hash['callback_uri'] : nil

      # Create object from extracted values.
      CallbackURI.new(callback_transport,
                      callback_uri)
    end
  end
end
