# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # DirectDebitWithReturn Model.
  class DirectDebitWithReturn < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [DirectDebit]
    attr_accessor :direct_debit

    # TODO: Write general description for this method
    # @return [DirectDebitReturn]
    attr_accessor :direct_debit_return

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['direct_debit'] = 'direct_debit'
      @_hash['direct_debit_return'] = 'direct_debit_return'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        direct_debit
        direct_debit_return
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(direct_debit = SKIP,
                   direct_debit_return = SKIP)
      @direct_debit = direct_debit unless direct_debit == SKIP
      @direct_debit_return = direct_debit_return unless direct_debit_return == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      direct_debit = DirectDebit.from_hash(hash['direct_debit']) if hash['direct_debit']
      direct_debit_return = DirectDebitReturn.from_hash(hash['direct_debit_return']) if
        hash['direct_debit_return']

      # Create object from extracted values.
      DirectDebitWithReturn.new(direct_debit,
                                direct_debit_return)
    end
  end
end
