# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # DirectDebitDecisionAdmissionStatusReason.
  class DirectDebitDecisionAdmissionStatusReasonEnum
    DIRECT_DEBIT_DECISION_ADMISSION_STATUS_REASON_ENUM = [
      # TODO: Write general description for ACCEPTED
      ACCEPTED = 'accepted'.freeze,

      # TODO: Write general description for INVALID_BENEFICIARY_DETAILS
      INVALID_BENEFICIARY_DETAILS = 'invalid_beneficiary_details'.freeze,

      # TODO: Write general description for BANKID_NOT_PROVISIONED
      BANKID_NOT_PROVISIONED = 'bankid_not_provisioned'.freeze,

      # TODO: Write general description for UNKNOWN_ACCOUNTNUMBER
      UNKNOWN_ACCOUNTNUMBER = 'unknown_accountnumber'.freeze,

      # TODO: Write general description for PENDING_SETTLEMENT
      PENDING_SETTLEMENT = 'pending_settlement'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      DIRECT_DEBIT_DECISION_ADMISSION_STATUS_REASON_ENUM.include?(value)
    end
  end
end
