# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # FPS Model.
  class FPS < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :accepts_payments

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :handling_bank_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :handling_bank_connection

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :service_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['accepts_payments'] = 'accepts_payments'
      @_hash['handling_bank_code'] = 'handling_bank_code'
      @_hash['handling_bank_connection'] = 'handling_bank_connection'
      @_hash['service_status'] = 'service_status'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        accepts_payments
        handling_bank_code
        handling_bank_connection
        service_status
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(accepts_payments = false,
                   handling_bank_code = SKIP,
                   handling_bank_connection = SKIP,
                   service_status = SKIP)
      @accepts_payments = accepts_payments unless accepts_payments == SKIP
      @handling_bank_code = handling_bank_code unless handling_bank_code == SKIP
      @handling_bank_connection = handling_bank_connection unless handling_bank_connection == SKIP
      @service_status = service_status unless service_status == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      accepts_payments = hash['accepts_payments'] ||= false
      handling_bank_code =
        hash.key?('handling_bank_code') ? hash['handling_bank_code'] : SKIP
      handling_bank_connection =
        hash.key?('handling_bank_connection') ? hash['handling_bank_connection'] : SKIP
      service_status =
        hash.key?('service_status') ? hash['service_status'] : SKIP

      # Create object from extracted values.
      FPS.new(accepts_payments,
              handling_bank_code,
              handling_bank_connection,
              service_status)
    end
  end
end
