# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Identification1 Model.
  class Identification1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :bank_id_code

    # TODO: Write general description for this method
    # @return [Array[RequestForInformationAgentBankId]]
    attr_accessor :bank_ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['bank_id'] = 'bank_id'
      @_hash['bank_id_code'] = 'bank_id_code'
      @_hash['bank_ids'] = 'bank_ids'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        bank_id
        bank_id_code
        bank_ids
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(bank_id = SKIP,
                   bank_id_code = SKIP,
                   bank_ids = SKIP)
      @bank_id = bank_id unless bank_id == SKIP
      @bank_id_code = bank_id_code unless bank_id_code == SKIP
      @bank_ids = bank_ids unless bank_ids == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      bank_id = hash.key?('bank_id') ? hash['bank_id'] : SKIP
      bank_id_code = hash.key?('bank_id_code') ? hash['bank_id_code'] : SKIP
      # Parameter is an array, so we need to iterate through it
      bank_ids = nil
      unless hash['bank_ids'].nil?
        bank_ids = []
        hash['bank_ids'].each do |structure|
          bank_ids << (RequestForInformationAgentBankId.from_hash(structure) if structure)
        end
      end

      bank_ids = SKIP unless hash.key?('bank_ids')

      # Create object from extracted values.
      Identification1.new(bank_id,
                          bank_id_code,
                          bank_ids)
    end
  end
end
