# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # MandateResourceType.
  class MandateResourceTypeEnum
    MANDATE_RESOURCE_TYPE_ENUM = [
      # TODO: Write general description for MANDATES
      MANDATES = 'mandates'.freeze,

      # TODO: Write general description for MANDATE_ADMISSIONS
      MANDATE_ADMISSIONS = 'mandate_admissions'.freeze,

      # TODO: Write general description for MANDATE_RETURNS
      MANDATE_RETURNS = 'mandate_returns'.freeze,

      # TODO: Write general description for MANDATE_RETURN_SUBMISSIONS
      MANDATE_RETURN_SUBMISSIONS = 'mandate_return_submissions'.freeze,

      # TODO: Write general description for
      # MANDATE_RETURN_SUBMISSION_VALIDATIONS
      MANDATE_RETURN_SUBMISSION_VALIDATIONS = 'mandate_return_submission_validations'.freeze,

      # TODO: Write general description for MANDATE_SUBMISSIONS
      MANDATE_SUBMISSIONS = 'mandate_submissions'.freeze,

      # TODO: Write general description for MANDATE_SUBMISSION_VALIDATIONS
      MANDATE_SUBMISSION_VALIDATIONS = 'mandate_submission_validations'.freeze,

      # TODO: Write general description for MANDATE_AUTOMATIC_RETURNS
      MANDATE_AUTOMATIC_RETURNS = 'mandate_automatic_returns'.freeze,

      # TODO: Write general description for MANDATE_MANAGEMENTS
      MANDATE_MANAGEMENTS = 'mandate_managements'.freeze,

      # TODO: Write general description for MANDATE_SUBMISSIONS_WITH_FINAL_STATE
      MANDATE_SUBMISSIONS_WITH_FINAL_STATE = 'mandate_submissions_with_final_state'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      MANDATE_RESOURCE_TYPE_ENUM.include?(value)
    end
  end
end
