# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # MandateStatus.
  class MandateStatusEnum
    MANDATE_STATUS_ENUM = [
      # TODO: Write general description for LIVE
      LIVE = 'live'.freeze,

      # TODO: Write general description for INVALID
      INVALID = 'invalid'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'expired'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'cancelled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      MANDATE_STATUS_ENUM.include?(value)
    end
  end
end
