# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Method used to settle the payment instruction. Acceptable Values for SEPA:
  # CLRG. Acceptable Values for SWIFT: INDA (settled by Instructed Agent), INGA
  # (Settled by Instructing Agent), COVE (Cover Payment)
  class MethodEnum
    METHOD_ENUM = [
      # TODO: Write general description for CLRG
      CLRG = 'CLRG'.freeze,

      # TODO: Write general description for COVE
      COVE = 'COVE'.freeze,

      # TODO: Write general description for INGA
      INGA = 'INGA'.freeze,

      # TODO: Write general description for INDA
      INDA = 'INDA'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      METHOD_ENUM.include?(value)
    end
  end
end
