# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # NameVerificationSubmissionReasonCode.
  class NameVerificationSubmissionReasonCodeEnum
    NAME_VERIFICATION_SUBMISSION_REASON_CODE_ENUM = [
      # TODO: Write general description for ANNM
      ANNM = 'ANNM'.freeze,

      # TODO: Write general description for MBAM
      MBAM = 'MBAM'.freeze,

      # TODO: Write general description for BANM
      BANM = 'BANM'.freeze,

      # TODO: Write general description for PANM
      PANM = 'PANM'.freeze,

      # TODO: Write general description for BAMM
      BAMM = 'BAMM'.freeze,

      # TODO: Write general description for PAMM
      PAMM = 'PAMM'.freeze,

      # TODO: Write general description for AC01
      AC01 = 'AC01'.freeze,

      # TODO: Write general description for IVCR
      IVCR = 'IVCR'.freeze,

      # TODO: Write general description for CASS
      CASS = 'CASS'.freeze,

      # TODO: Write general description for SCNS
      SCNS = 'SCNS'.freeze,

      # TODO: Write general description for ACNS
      ACNS = 'ACNS'.freeze,

      # TODO: Write general description for OPTO
      OPTO = 'OPTO'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAME_VERIFICATION_SUBMISSION_REASON_CODE_ENUM.include?(value)
    end
  end
end
