# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # NewReportRequestAttributes Model.
  class NewReportRequestAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [NewReportRequestFilter]
    attr_accessor :filter

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :payment_scheme

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :report_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['filter'] = 'filter'
      @_hash['payment_scheme'] = 'payment_scheme'
      @_hash['report_type'] = 'report_type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(filter = nil,
                   payment_scheme = nil,
                   report_type = nil)
      @filter = filter
      @payment_scheme = payment_scheme
      @report_type = report_type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      filter = NewReportRequestFilter.from_hash(hash['filter']) if hash['filter']
      payment_scheme =
        hash.key?('payment_scheme') ? hash['payment_scheme'] : nil
      report_type = hash.key?('report_type') ? hash['report_type'] : nil

      # Create object from extracted values.
      NewReportRequestAttributes.new(filter,
                                     payment_scheme,
                                     report_type)
    end
  end
end
