# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Scheme/gateway that the file is to be processed by
  class PaymentScheme2Enum
    PAYMENT_SCHEME2_ENUM = [
      # TODO: Write general description for CASS
      CASS = 'CASS'.freeze,

      # TODO: Write general description for CISA
      CISA = 'CISA'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_SCHEME2_ENUM.include?(value)
    end
  end
end
