# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # PaymentAdmissionResourceType.
  class PaymentAdmissionResourceTypeEnum
    PAYMENT_ADMISSION_RESOURCE_TYPE_ENUM = [
      # TODO: Write general description for PAYMENT_ADMISSIONS
      PAYMENT_ADMISSIONS = 'payment_admissions'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_ADMISSION_RESOURCE_TYPE_ENUM.include?(value)
    end
  end
end
