# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Helps to identify the owner of the task
  class PaymentSubmissionTaskAssigneeEnum
    PAYMENT_SUBMISSION_TASK_ASSIGNEE_ENUM = [
      # TODO: Write general description for FORM3
      FORM3 = 'form3'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_SUBMISSION_TASK_ASSIGNEE_ENUM.include?(value)
    end
  end
end
