# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # [Payment admission status
  # reason](https://api-docs.form3.tech/api.html#enumerations-payment-status-cod
  # es-payment-admission-status-reasons)
  class PaymentAdmissionStatusReasonEnum
    PAYMENT_ADMISSION_STATUS_REASON_ENUM = [
      # TODO: Write general description for ACCEPTED
      ACCEPTED = 'accepted'.freeze,

      # TODO: Write general description for INVALID_BENEFICIARY_DETAILS
      INVALID_BENEFICIARY_DETAILS = 'invalid_beneficiary_details'.freeze,

      # TODO: Write general description for BANKID_NOT_PROVISIONED
      BANKID_NOT_PROVISIONED = 'bankid_not_provisioned'.freeze,

      # TODO: Write general description for UNKNOWN_ACCOUNTNUMBER
      UNKNOWN_ACCOUNTNUMBER = 'unknown_accountnumber'.freeze,

      # TODO: Write general description for CUSTOMER_CHECK_FAILED
      CUSTOMER_CHECK_FAILED = 'customer_check_failed'.freeze,

      # TODO: Write general description for SCHEME_TIMEOUT
      SCHEME_TIMEOUT = 'scheme_timeout'.freeze,

      # TODO: Write general description for INCORRECT_REFERENCE_VALIDATION_TYPE
      INCORRECT_REFERENCE_VALIDATION_TYPE = 'incorrect_reference_validation_type'.freeze,

      # TODO: Write general description for
      # INCORRECT_REFERENCE_SECONDARY_IDENTIFICATION
      INCORRECT_REFERENCE_SECONDARY_IDENTIFICATION = 'incorrect_reference_secondary_identification'.freeze,

      # TODO: Write general description for INCORRECT_REFERENCE_REFERENCE_MASK
      INCORRECT_REFERENCE_REFERENCE_MASK = 'incorrect_reference_reference_mask'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED
      ACCOUNT_CLOSED = 'account_closed'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_BUSINESS_REASONS
      ACCOUNT_CLOSED_BUSINESS_REASONS = 'account_closed_business_reasons'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_STOPPED
      ACCOUNT_CLOSED_STOPPED = 'account_closed_stopped'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_CURRENCY
      ACCOUNT_CLOSED_CURRENCY = 'account_closed_currency'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_TRANSFERRED
      ACCOUNT_CLOSED_TRANSFERRED = 'account_closed_transferred'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_BENEFICIARY_DECEASED
      ACCOUNT_CLOSED_BENEFICIARY_DECEASED = 'account_closed_beneficiary_deceased'.freeze,

      # TODO: Write general description for
      # ACCOUNT_CLOSED_BENEFICIARY_SENSITIVITIES
      ACCOUNT_CLOSED_BENEFICIARY_SENSITIVITIES = 'account_closed_beneficiary_sensitivities'.freeze,

      # TODO: Write general description for ACCOUNT_CLOSED_TERMS_AND_CONDITIONS
      ACCOUNT_CLOSED_TERMS_AND_CONDITIONS = 'account_closed_terms_and_conditions'.freeze,

      # TODO: Write general description for
      # BENEFICIARY_AGENT_CLEARING_PROCESS_TIMEOUT
      BENEFICIARY_AGENT_CLEARING_PROCESS_TIMEOUT = 'beneficiary_agent_clearing_process_timeout'.freeze,

      # TODO: Write general description for AGENT_CLEARING_PROCESS_TIMEOUT
      AGENT_CLEARING_PROCESS_TIMEOUT = 'agent_clearing_process_timeout'.freeze,

      # TODO: Write general description for AGENT_UNAVAILABLE
      AGENT_UNAVAILABLE = 'agent_unavailable'.freeze,

      # TODO: Write general description for BENEFICIARY_AGENT_UNAVAILABLE
      BENEFICIARY_AGENT_UNAVAILABLE = 'beneficiary_agent_unavailable'.freeze,

      # TODO: Write general description for
      # BENEFICIARY_AGENT_CLEARING_PROCESS_ERROR
      BENEFICIARY_AGENT_CLEARING_PROCESS_ERROR = 'beneficiary_agent_clearing_process_error'.freeze,

      # TODO: Write general description for AGENT_CLEARING_PROCESS_ERROR
      AGENT_CLEARING_PROCESS_ERROR = 'agent_clearing_process_error'.freeze,

      # TODO: Write general description for BLOCKED_ACCOUNT
      BLOCKED_ACCOUNT = 'blocked_account'.freeze,

      # TODO: Write general description for TRANSACTION_FORBIDDEN
      TRANSACTION_FORBIDDEN = 'transaction_forbidden'.freeze,

      # TODO: Write general description for INVALID_BANK_OPERATION_CODE
      INVALID_BANK_OPERATION_CODE = 'invalid_bank_operation_code'.freeze,

      # TODO: Write general description for ORIGINAL_PAYMENT_NOT_RECEIVED
      ORIGINAL_PAYMENT_NOT_RECEIVED = 'original_payment_not_received'.freeze,

      # TODO: Write general description for AGENT_SUSPENDED
      AGENT_SUSPENDED = 'agent_suspended'.freeze,

      # TODO: Write general description for BENEFICIARY_AGENT_SUSPENDED
      BENEFICIARY_AGENT_SUSPENDED = 'beneficiary_agent_suspended'.freeze,

      # TODO: Write general description for AMOUNT_NOT_ALLOWED
      AMOUNT_NOT_ALLOWED = 'amount_not_allowed'.freeze,

      # TODO: Write general description for DUPLICATE_PAYMENT
      DUPLICATE_PAYMENT = 'duplicate_payment'.freeze,

      # TODO: Write general description for AMOUNT_EXCEEDS_SETTLEMENT_LIMIT
      AMOUNT_EXCEEDS_SETTLEMENT_LIMIT = 'amount_exceeds_settlement_limit'.freeze,

      # TODO: Write general description for INVALID_BENEFICIARY_ADDRESS
      INVALID_BENEFICIARY_ADDRESS = 'invalid_beneficiary_address'.freeze,

      # TODO: Write general description for INVALID_BENEFICIARY_AGENT_BIC
      INVALID_BENEFICIARY_AGENT_BIC = 'invalid_beneficiary_agent_BIC'.freeze,

      # TODO: Write general description for INVALID_DEBTOR_AGENT_BIC
      INVALID_DEBTOR_AGENT_BIC = 'invalid_debtor_agent_BIC'.freeze,

      # TODO: Write general description for CUSTOMER_REASON_UNKNOWN
      CUSTOMER_REASON_UNKNOWN = 'customer_reason_unknown'.freeze,

      # TODO: Write general description for AGENT_REASON_UNKNOWN
      AGENT_REASON_UNKNOWN = 'agent_reason_unknown'.freeze,

      # TODO: Write general description for INVALID_BANK_ID
      INVALID_BANK_ID = 'invalid_bank_ID'.freeze,

      # TODO: Write general description for INVALID_DEBTOR_DETAILS
      INVALID_DEBTOR_DETAILS = 'invalid_debtor_details'.freeze,

      # TODO: Write general description for REGULATORY_REASON
      REGULATORY_REASON = 'regulatory_reason'.freeze,

      # TODO: Write general description for AMOUNT_INVALID_OR_MISSING
      AMOUNT_INVALID_OR_MISSING = 'amount_invalid_or_missing'.freeze,

      # TODO: Write general description for END_TO_END_ID_MISSING_OR_INVALID
      END_TO_END_ID_MISSING_OR_INVALID = 'end_to_end_id_missing_or_invalid'.freeze,

      # TODO: Write general description for TRANSACTION_TYPE_NOT_SUPPORTED
      TRANSACTION_TYPE_NOT_SUPPORTED = 'transaction_type_not_supported'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PAYMENT_ADMISSION_STATUS_REASON_ENUM.include?(value)
    end
  end
end
