# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # PrivateIdentification1 Model.
  class PrivateIdentification1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :private_identification_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :private_identification_identification

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :private_identification_issuer

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['private_identification_code'] = 'private_identification.code'
      @_hash['private_identification_identification'] =
        'private_identification.identification'
      @_hash['private_identification_issuer'] =
        'private_identification.issuer'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        private_identification_code
        private_identification_identification
        private_identification_issuer
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(private_identification_code = SKIP,
                   private_identification_identification = SKIP,
                   private_identification_issuer = SKIP)
      unless private_identification_code == SKIP
        @private_identification_code =
          private_identification_code
      end
      unless private_identification_identification == SKIP
        @private_identification_identification =
          private_identification_identification
      end
      unless private_identification_issuer == SKIP
        @private_identification_issuer =
          private_identification_issuer
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      private_identification_code =
        hash.key?('private_identification.code') ? hash['private_identification.code'] : SKIP
      private_identification_identification =
        hash.key?('private_identification.identification') ? hash['private_identification.identification'] : SKIP
      private_identification_issuer =
        hash.key?('private_identification.issuer') ? hash['private_identification.issuer'] : SKIP

      # Create object from extracted values.
      PrivateIdentification1.new(private_identification_code,
                                 private_identification_identification,
                                 private_identification_issuer)
    end
  end
end
