# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # QueryResponseAdmissionAttributes Model.
  class QueryResponseAdmissionAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [QueryResponseAdmissionStatusEnum]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status_reason

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['status_reason'] = 'status_reason'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        status_reason
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(status = nil,
                   status_reason = SKIP)
      @status = status
      @status_reason = status_reason unless status_reason == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash.key?('status') ? hash['status'] : nil
      status_reason = hash.key?('status_reason') ? hash['status_reason'] : SKIP

      # Create object from extracted values.
      QueryResponseAdmissionAttributes.new(status,
                                           status_reason)
    end
  end
end
