# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # QueryResponseAdmissionResourceType.
  class QueryResponseAdmissionResourceTypeEnum
    QUERY_RESPONSE_ADMISSION_RESOURCE_TYPE_ENUM = [
      # TODO: Write general description for QUERY_RESPONSE_ADMISSIONS
      QUERY_RESPONSE_ADMISSIONS = 'query_response_admissions'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      QUERY_RESPONSE_ADMISSION_RESOURCE_TYPE_ENUM.include?(value)
    end
  end
end
