# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # QueryResponseRelationships Model.
  class QueryResponseRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipsFullQuery]
    attr_accessor :query

    # TODO: Write general description for this method
    # @return [RelationshipQueryResponseAdmission]
    attr_accessor :query_response_admission

    # TODO: Write general description for this method
    # @return [RelationshipQueryResponseSubmission]
    attr_accessor :query_response_submission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['query'] = 'query'
      @_hash['query_response_admission'] = 'query_response_admission'
      @_hash['query_response_submission'] = 'query_response_submission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        query
        query_response_admission
        query_response_submission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(query = SKIP,
                   query_response_admission = SKIP,
                   query_response_submission = SKIP)
      @query = query unless query == SKIP
      @query_response_admission = query_response_admission unless query_response_admission == SKIP
      unless query_response_submission == SKIP
        @query_response_submission =
          query_response_submission
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      query = RelationshipsFullQuery.from_hash(hash['query']) if hash['query']
      if hash['query_response_admission']
        query_response_admission = RelationshipQueryResponseAdmission.from_hash(hash['query_response_admission'])
      end
      if hash['query_response_submission']
        query_response_submission = RelationshipQueryResponseSubmission.from_hash(hash['query_response_submission'])
      end

      # Create object from extracted values.
      QueryResponseRelationships.new(query,
                                     query_response_admission,
                                     query_response_submission)
    end
  end
end
