# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # The type of identification given at `account_number` attribute
  class QueryAccountNumberCodeEnum
    QUERY_ACCOUNT_NUMBER_CODE_ENUM = [
      # TODO: Write general description for IBAN
      IBAN = 'IBAN'.freeze,

      # TODO: Write general description for BBAN
      BBAN = 'BBAN'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      QUERY_ACCOUNT_NUMBER_CODE_ENUM.include?(value)
    end
  end
end
