# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # QueryAdmissionRelationships Model.
  class QueryAdmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipsFullQuery]
    attr_accessor :query

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['query'] = 'query'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(query = nil)
      @query = query
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      query = RelationshipsFullQuery.from_hash(hash['query']) if hash['query']

      # Create object from extracted values.
      QueryAdmissionRelationships.new(query)
    end
  end
end
