# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RecallAdmissionRelationships Model.
  class RecallAdmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipPayments]
    attr_accessor :payment

    # TODO: Write general description for this method
    # @return [RelationshipRecalls]
    attr_accessor :recall

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment'] = 'payment'
      @_hash['recall'] = 'recall'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payment
        recall
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment = SKIP,
                   recall = SKIP)
      @payment = payment unless payment == SKIP
      @recall = recall unless recall == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment = RelationshipPayments.from_hash(hash['payment']) if hash['payment']
      recall = RelationshipRecalls.from_hash(hash['recall']) if hash['recall']

      # Create object from extracted values.
      RecallAdmissionRelationships.new(payment,
                                       recall)
    end
  end
end
