# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module Form3PublicApi
  # RecallDecisionSubmissionAttributes Model.
  class RecallDecisionSubmissionAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Indicates if the submission was created automatically by the system
    # (`true`) or manually (`false`).
    # @return [TrueClass | FalseClass]
    attr_accessor :auto

    # [Status](http://draft-api-docs.form3.tech/api.html#enumerations-payment-st
    # atus-codes-payment-submission-status) of the submission
    # @return [RecallDecisionSubmissionStatusEnum]
    attr_accessor :status

    # Reason for submission failure if status is `delivery_failed`
    # @return [String]
    attr_accessor :status_reason

    # Date and time of the submission
    # @return [DateTime]
    attr_accessor :submission_datetime

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['auto'] = 'auto'
      @_hash['status'] = 'status'
      @_hash['status_reason'] = 'status_reason'
      @_hash['submission_datetime'] = 'submission_datetime'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        auto
        status
        status_reason
        submission_datetime
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(auto = false,
                   status = SKIP,
                   status_reason = SKIP,
                   submission_datetime = SKIP)
      @auto = auto unless auto == SKIP
      @status = status unless status == SKIP
      @status_reason = status_reason unless status_reason == SKIP
      @submission_datetime = submission_datetime unless submission_datetime == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      auto = hash['auto'] ||= false
      status = hash.key?('status') ? hash['status'] : SKIP
      status_reason = hash.key?('status_reason') ? hash['status_reason'] : SKIP
      submission_datetime = if hash.key?('submission_datetime')
                              (DateTimeHelper.from_rfc3339(hash['submission_datetime']) if hash['submission_datetime'])
                            else
                              SKIP
                            end

      # Create object from extracted values.
      RecallDecisionSubmissionAttributes.new(auto,
                                             status,
                                             status_reason,
                                             submission_datetime)
    end

    def to_custom_submission_datetime
      DateTimeHelper.to_rfc3339(submission_datetime)
    end
  end
end
