# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RecallReversalAdmissionAttributes Model.
  class RecallReversalAdmissionAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Scheme-specific status code
    # @return [String]
    attr_accessor :scheme_status_code

    # Scheme-specific status code
    # @return [String]
    attr_accessor :source_gateway

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['scheme_status_code'] = 'scheme_status_code'
      @_hash['source_gateway'] = 'source_gateway'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        scheme_status_code
        source_gateway
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(scheme_status_code = SKIP,
                   source_gateway = SKIP)
      @scheme_status_code = scheme_status_code unless scheme_status_code == SKIP
      @source_gateway = source_gateway unless source_gateway == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      scheme_status_code =
        hash.key?('scheme_status_code') ? hash['scheme_status_code'] : SKIP
      source_gateway =
        hash.key?('source_gateway') ? hash['source_gateway'] : SKIP

      # Create object from extracted values.
      RecallReversalAdmissionAttributes.new(scheme_status_code,
                                            source_gateway)
    end
  end
end
