# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RecallDecisionSubmissionRelationships Model.
  class RecallDecisionSubmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipPayments]
    attr_accessor :payment

    # TODO: Write general description for this method
    # @return [RelationshipRecalls]
    attr_accessor :recall

    # TODO: Write general description for this method
    # @return [RelationshipRecallDecisions]
    attr_accessor :recall_decision

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment'] = 'payment'
      @_hash['recall'] = 'recall'
      @_hash['recall_decision'] = 'recall_decision'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payment
        recall
        recall_decision
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment = SKIP,
                   recall = SKIP,
                   recall_decision = SKIP)
      @payment = payment unless payment == SKIP
      @recall = recall unless recall == SKIP
      @recall_decision = recall_decision unless recall_decision == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment = RelationshipPayments.from_hash(hash['payment']) if hash['payment']
      recall = RelationshipRecalls.from_hash(hash['recall']) if hash['recall']
      recall_decision = RelationshipRecallDecisions.from_hash(hash['recall_decision']) if
        hash['recall_decision']

      # Create object from extracted values.
      RecallDecisionSubmissionRelationships.new(payment,
                                                recall,
                                                recall_decision)
    end
  end
end
