# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Reference Model.
  class Reference < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Name of the reference type
    # @return [String]
    attr_accessor :type

    # Value of the provided reference type
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['value'] = 'value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(type = nil,
                   value = nil)
      @type = type
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash.key?('type') ? hash['type'] : nil
      value = hash.key?('value') ? hash['value'] : nil

      # Create object from extracted values.
      Reference.new(type,
                    value)
    end
  end
end
