# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Relationships10 Model.
  class Relationships10 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [DirectDebit1]
    attr_accessor :direct_debit

    # TODO: Write general description for this method
    # @return [DirectDebitReturnAdmission2]
    attr_accessor :direct_debit_return_admission

    # TODO: Write general description for this method
    # @return [DirectDebitReturnReversal2]
    attr_accessor :direct_debit_return_reversal

    # TODO: Write general description for this method
    # @return [DirectDebitReturnSubmission2]
    attr_accessor :direct_debit_return_submission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['direct_debit'] = 'direct_debit'
      @_hash['direct_debit_return_admission'] =
        'direct_debit_return_admission'
      @_hash['direct_debit_return_reversal'] = 'direct_debit_return_reversal'
      @_hash['direct_debit_return_submission'] =
        'direct_debit_return_submission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        direct_debit
        direct_debit_return_admission
        direct_debit_return_reversal
        direct_debit_return_submission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(direct_debit = SKIP,
                   direct_debit_return_admission = SKIP,
                   direct_debit_return_reversal = SKIP,
                   direct_debit_return_submission = SKIP)
      @direct_debit = direct_debit unless direct_debit == SKIP
      unless direct_debit_return_admission == SKIP
        @direct_debit_return_admission =
          direct_debit_return_admission
      end
      unless direct_debit_return_reversal == SKIP
        @direct_debit_return_reversal =
          direct_debit_return_reversal
      end
      unless direct_debit_return_submission == SKIP
        @direct_debit_return_submission =
          direct_debit_return_submission
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      direct_debit = DirectDebit1.from_hash(hash['direct_debit']) if hash['direct_debit']
      if hash['direct_debit_return_admission']
        direct_debit_return_admission = DirectDebitReturnAdmission2.from_hash(hash['direct_debit_return_admission'])
      end
      if hash['direct_debit_return_reversal']
        direct_debit_return_reversal = DirectDebitReturnReversal2.from_hash(hash['direct_debit_return_reversal'])
      end
      if hash['direct_debit_return_submission']
        direct_debit_return_submission = DirectDebitReturnSubmission2.from_hash(hash['direct_debit_return_submission'])
      end

      # Create object from extracted values.
      Relationships10.new(direct_debit,
                          direct_debit_return_admission,
                          direct_debit_return_reversal,
                          direct_debit_return_submission)
    end
  end
end
