# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Relationships1 Model.
  class Relationships1 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :advice_submission

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :payment

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['advice_submission'] = 'advice_submission'
      @_hash['payment'] = 'payment'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        advice_submission
        payment
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(advice_submission = SKIP,
                   payment = SKIP)
      @advice_submission = advice_submission unless advice_submission == SKIP
      @payment = payment unless payment == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      advice_submission = RelationshipLinks.from_hash(hash['advice_submission']) if
        hash['advice_submission']
      payment = RelationshipLinks.from_hash(hash['payment']) if hash['payment']

      # Create object from extracted values.
      Relationships1.new(advice_submission,
                         payment)
    end
  end
end
