# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Relationships17 Model.
  class Relationships17 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Mandate2]
    attr_accessor :mandate

    # TODO: Write general description for this method
    # @return [MandateReturnSubmission2]
    attr_accessor :mandate_return_submission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['mandate'] = 'mandate'
      @_hash['mandate_return_submission'] = 'mandate_return_submission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        mandate
        mandate_return_submission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(mandate = SKIP,
                   mandate_return_submission = SKIP)
      @mandate = mandate unless mandate == SKIP
      unless mandate_return_submission == SKIP
        @mandate_return_submission =
          mandate_return_submission
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      mandate = Mandate2.from_hash(hash['mandate']) if hash['mandate']
      if hash['mandate_return_submission']
        mandate_return_submission = MandateReturnSubmission2.from_hash(hash['mandate_return_submission'])
      end

      # Create object from extracted values.
      Relationships17.new(mandate,
                          mandate_return_submission)
    end
  end
end
