# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Relationships21 Model.
  class Relationships21 < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :payment

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :recall

    # TODO: Write general description for this method
    # @return [RelationshipLinks]
    attr_accessor :reversal_admission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment'] = 'payment'
      @_hash['recall'] = 'recall'
      @_hash['reversal_admission'] = 'reversal_admission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payment
        recall
        reversal_admission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment = SKIP,
                   recall = SKIP,
                   reversal_admission = SKIP)
      @payment = payment unless payment == SKIP
      @recall = recall unless recall == SKIP
      @reversal_admission = reversal_admission unless reversal_admission == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment = RelationshipLinks.from_hash(hash['payment']) if hash['payment']
      recall = RelationshipLinks.from_hash(hash['recall']) if hash['recall']
      reversal_admission = RelationshipLinks.from_hash(hash['reversal_admission']) if
        hash['reversal_admission']

      # Create object from extracted values.
      Relationships21.new(payment,
                          recall,
                          reversal_admission)
    end
  end
end
