# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Relationships Model.
  class Relationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [SortCode]
    attr_accessor :sort_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sort_code'] = 'sort_code'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sort_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(sort_code = SKIP)
      @sort_code = sort_code unless sort_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sort_code = SortCode.from_hash(hash['sort_code']) if hash['sort_code']

      # Create object from extracted values.
      Relationships.new(sort_code)
    end
  end
end
