# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # ReportRequestRelationships Model.
  class ReportRequestRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Report1]
    attr_accessor :report

    # TODO: Write general description for this method
    # @return [ReportRequestSubmission2]
    attr_accessor :report_request_submission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['report'] = 'report'
      @_hash['report_request_submission'] = 'report_request_submission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        report
        report_request_submission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(report = SKIP,
                   report_request_submission = SKIP)
      @report = report unless report == SKIP
      unless report_request_submission == SKIP
        @report_request_submission =
          report_request_submission
      end
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      report = Report1.from_hash(hash['report']) if hash['report']
      if hash['report_request_submission']
        report_request_submission = ReportRequestSubmission2.from_hash(hash['report_request_submission'])
      end

      # Create object from extracted values.
      ReportRequestRelationships.new(report,
                                     report_request_submission)
    end
  end
end
