# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # ReportRequestUserIdCode.
  class ReportRequestUserIdCodeEnum
    REPORT_REQUEST_USER_ID_CODE_ENUM = [
      # TODO: Write general description for SWBIC
      SWBIC = 'SWBIC'.freeze,

      # TODO: Write general description for RTN
      RTN = 'RTN'.freeze,

      # TODO: Write general description for PARTICIPANT
      PARTICIPANT = 'Participant'.freeze,

      # TODO: Write general description for SUN
      SUN = 'SUN'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      REPORT_REQUEST_USER_ID_CODE_ENUM.include?(value)
    end
  end
end
