# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RequestForInformationAgent Model.
  class RequestForInformationAgent < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Identification1]
    attr_accessor :identification

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :role

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['identification'] = 'identification'
      @_hash['role'] = 'role'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        identification
        role
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(identification = SKIP,
                   role = SKIP)
      @identification = identification unless identification == SKIP
      @role = role unless role == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      identification = Identification1.from_hash(hash['identification']) if hash['identification']
      role = hash.key?('role') ? hash['role'] : SKIP

      # Create object from extracted values.
      RequestForInformationAgent.new(identification,
                                     role)
    end
  end
end
