# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RequestForInformationRequestedInformation Model.
  class RequestForInformationRequestedInformation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :additional_information

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :code

    # TODO: Write general description for this method
    # @return [Type6Enum]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['additional_information'] = 'additional_information'
      @_hash['code'] = 'code'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        additional_information
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(code = nil,
                   type = nil,
                   additional_information = SKIP)
      @additional_information = additional_information unless additional_information == SKIP
      @code = code
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash.key?('code') ? hash['code'] : nil
      type = hash.key?('type') ? hash['type'] : nil
      additional_information =
        hash.key?('additional_information') ? hash['additional_information'] : SKIP

      # Create object from extracted values.
      RequestForInformationRequestedInformation.new(code,
                                                    type,
                                                    additional_information)
    end
  end
end
