# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # ReturnSubmissionUpdateRelationships Model.
  class ReturnSubmissionUpdateRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ReturnSubmissionTask]]
    attr_accessor :return_submission_tasks

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['return_submission_tasks'] = 'return_submission_tasks'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        return_submission_tasks
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(return_submission_tasks = SKIP)
      @return_submission_tasks = return_submission_tasks unless return_submission_tasks == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      return_submission_tasks = nil
      unless hash['return_submission_tasks'].nil?
        return_submission_tasks = []
        hash['return_submission_tasks'].each do |structure|
          return_submission_tasks << (ReturnSubmissionTask.from_hash(structure) if structure)
        end
      end

      return_submission_tasks = SKIP unless hash.key?('return_submission_tasks')

      # Create object from extracted values.
      ReturnSubmissionUpdateRelationships.new(return_submission_tasks)
    end
  end
end
