# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # ReturnReversalAdmissionRelationships Model.
  class ReturnReversalAdmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [RelationshipPayments]
    attr_accessor :payment

    # TODO: Write general description for this method
    # @return [RelationshipReturns]
    attr_accessor :payment_return

    # TODO: Write general description for this method
    # @return [RelationshipReturnReversals]
    attr_accessor :payment_return_reversal

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['payment'] = 'payment'
      @_hash['payment_return'] = 'payment_return'
      @_hash['payment_return_reversal'] = 'payment_return_reversal'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        payment
        payment_return
        payment_return_reversal
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(payment = SKIP,
                   payment_return = SKIP,
                   payment_return_reversal = SKIP)
      @payment = payment unless payment == SKIP
      @payment_return = payment_return unless payment_return == SKIP
      @payment_return_reversal = payment_return_reversal unless payment_return_reversal == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      payment = RelationshipPayments.from_hash(hash['payment']) if hash['payment']
      payment_return = RelationshipReturns.from_hash(hash['payment_return']) if
        hash['payment_return']
      if hash['payment_return_reversal']
        payment_return_reversal = RelationshipReturnReversals.from_hash(hash['payment_return_reversal'])
      end

      # Create object from extracted values.
      ReturnReversalAdmissionRelationships.new(payment,
                                               payment_return,
                                               payment_return_reversal)
    end
  end
end
