# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # RoleAttributes Model.
  class RoleAttributes < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Name of the role
    # @return [String]
    attr_accessor :name

    # Unique resource ID of the parent Role
    # @return [UUID | String]
    attr_accessor :parent_role_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['name'] = 'name'
      @_hash['parent_role_id'] = 'parent_role_id'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        name
        parent_role_id
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(name = SKIP,
                   parent_role_id = SKIP)
      @name = name unless name == SKIP
      @parent_role_id = parent_role_id unless parent_role_id == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      name = hash.key?('name') ? hash['name'] : SKIP
      parent_role_id =
        hash.key?('parent_role_id') ? hash['parent_role_id'] : SKIP

      # Create object from extracted values.
      RoleAttributes.new(name,
                         parent_role_id)
    end
  end
end
