# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Route taken for an outbound payment
  class RouteEnum
    ROUTE_ENUM = [
      # TODO: Write general description for ON_US
      ON_US = 'on_us'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ROUTE_ENUM.include?(value)
    end
  end
end
