# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # SchemeFileRelationships Model.
  class SchemeFileRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [SchemeFileAdmissions]
    attr_accessor :scheme_file_admissions

    # TODO: Write general description for this method
    # @return [SchemeFileSubmission2]
    attr_accessor :scheme_file_submission

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['scheme_file_admissions'] = 'scheme_file_admissions'
      @_hash['scheme_file_submission'] = 'scheme_file_submission'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        scheme_file_admissions
        scheme_file_submission
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(scheme_file_admissions = SKIP,
                   scheme_file_submission = SKIP)
      @scheme_file_admissions = scheme_file_admissions unless scheme_file_admissions == SKIP
      @scheme_file_submission = scheme_file_submission unless scheme_file_submission == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      scheme_file_admissions = SchemeFileAdmissions.from_hash(hash['scheme_file_admissions']) if
        hash['scheme_file_admissions']
      scheme_file_submission = SchemeFileSubmission2.from_hash(hash['scheme_file_submission']) if
        hash['scheme_file_submission']

      # Create object from extracted values.
      SchemeFileRelationships.new(scheme_file_admissions,
                                  scheme_file_submission)
    end
  end
end
