# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # SchemeFileAdmissionRelationships Model.
  class SchemeFileAdmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [SchemeFiles]
    attr_accessor :scheme_files

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['scheme_files'] = 'scheme_files'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        scheme_files
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(scheme_files = SKIP)
      @scheme_files = scheme_files unless scheme_files == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      scheme_files = SchemeFiles.from_hash(hash['scheme_files']) if hash['scheme_files']

      # Create object from extracted values.
      SchemeFileAdmissionRelationships.new(scheme_files)
    end
  end
end
