# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # SchemeMessageAdmissionStatus.
  class SchemeMessageAdmissionStatusEnum
    SCHEME_MESSAGE_ADMISSION_STATUS_ENUM = [
      # TODO: Write general description for DELIVERY_CONFIRMED
      DELIVERY_CONFIRMED = 'delivery_confirmed'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SCHEME_MESSAGE_ADMISSION_STATUS_ENUM.include?(value)
    end
  end
end
