# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # SchemeMessageEntryItem Model.
  class SchemeMessageEntryItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :key

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['key'] = 'key'
      @_hash['value'] = 'value'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        value
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(key = nil,
                   value = SKIP)
      @key = key
      @value = value unless value == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      key = hash.key?('key') ? hash['key'] : nil
      value = hash.key?('value') ? hash['value'] : SKIP

      # Create object from extracted values.
      SchemeMessageEntryItem.new(key,
                                 value)
    end
  end
end
