# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Contains the event status
  class Status2Enum
    STATUS2_ENUM = [
      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for CONFIRMED
      CONFIRMED = 'confirmed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      STATUS2_ENUM.include?(value)
    end
  end
end
