# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # StructuredReference Model.
  class StructuredReference < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Issuer of remittance reference
    # @return [String]
    attr_accessor :issuer

    # Unique reference to unambiguously refer to the payment originated by the
    # creditor, this reference enables reconciliation by the creditor upon
    # receipt of the amount of money.
    # @return [String]
    attr_accessor :reference

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['issuer'] = 'issuer'
      @_hash['reference'] = 'reference'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        issuer
        reference
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(issuer = SKIP,
                   reference = SKIP)
      @issuer = issuer unless issuer == SKIP
      @reference = reference unless reference == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      issuer = hash.key?('issuer') ? hash['issuer'] : SKIP
      reference = hash.key?('reference') ? hash['reference'] : SKIP

      # Create object from extracted values.
      StructuredReference.new(issuer,
                              reference)
    end
  end
end
