# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # The type of the token. Is always set to `Bearer`.
  class TokenTypeEnum
    TOKEN_TYPE_ENUM = [
      # TODO: Write general description for BEARER
      BEARER = 'Bearer'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TOKEN_TYPE_ENUM.include?(value)
    end
  end
end
