# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # TransactionGroupCode.
  class TransactionGroupCodeEnum
    TRANSACTION_GROUP_CODE_ENUM = [
      # TODO: Write general description for DR
      DR = 'DR'.freeze,

      # TODO: Write general description for CR
      CR = 'CR'.freeze,

      # TODO: Write general description for CU
      CU = 'CU'.freeze,

      # TODO: Write general description for BS
      BS = 'BS'.freeze,

      # TODO: Write general description for DV
      DV = 'DV'.freeze,

      # TODO: Write general description for AU
      AU = 'AU'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TRANSACTION_GROUP_CODE_ENUM.include?(value)
    end
  end
end
