# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # TransactionFileSubmissionRelationships Model.
  class TransactionFileSubmissionRelationships < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TransactionFiles]
    attr_accessor :transaction_files

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['transaction_files'] = 'transaction_files'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        transaction_files
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(transaction_files = SKIP)
      @transaction_files = transaction_files unless transaction_files == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      transaction_files = TransactionFiles.from_hash(hash['transaction_files']) if
        hash['transaction_files']

      # Create object from extracted values.
      TransactionFileSubmissionRelationships.new(transaction_files)
    end
  end
end
