# form3_public_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Form3PublicApi
  # Type1.
  class Type1Enum
    TYPE1_ENUM = [
      # TODO: Write general description for SCHEME_FILE_SUBMISSIONS
      SCHEME_FILE_SUBMISSIONS = 'scheme_file_submissions'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE1_ENUM.include?(value)
    end
  end
end
